2024-09-16 01:50:20,023 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.14.2 Python/3.11.6 Linux/6.8.0-101041-tuxedo source/x86_64.ubuntu.22
2024-09-16 01:50:20,023 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'ls', '--debug', '--endpoint=https://us-southeast-1.linodeobjects.com']
2024-09-16 01:50:20,029 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_s3 at 0x78aa87b00220>
2024-09-16 01:50:20,029 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_ddb at 0x78aa87d30040>
2024-09-16 01:50:20,029 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.configure.configure.ConfigureCommand'>>
2024-09-16 01:50:20,029 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x78aa87e9c5e0>
2024-09-16 01:50:20,029 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function change_name at 0x78aa87e9f9c0>
2024-09-16 01:50:20,030 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function alias_opsworks_cm at 0x78aa87b02ca0>
2024-09-16 01:50:20,030 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_history_commands at 0x78aa87d76ac0>
2024-09-16 01:50:20,030 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method BasicCommand.add_command of <class 'awscli.customizations.devcommands.CLIDevCommand'>>
2024-09-16 01:50:20,030 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <function add_waiters at 0x78aa87b02b60>
2024-09-16 01:50:20,030 - MainThread - botocore.hooks - DEBUG - Event building-command-table.main: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x78aa87bc5c10>>
2024-09-16 01:50:20,030 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/data/cli.json
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_types at 0x78aa87c4c540>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function no_sign_request at 0x78aa87c4c860>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_verify_ssl at 0x78aa87c4c7c0>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_read_timeout at 0x78aa87c4c9a0>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <function resolve_cli_connect_timeout at 0x78aa87c4c900>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event top-level-args-parsed: calling handler <built-in method update of dict object at 0x78aa87bbedc0>
2024-09-16 01:50:20,031 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/2.14.2 Python/3.11.6 Linux/6.8.0-101041-tuxedo source/x86_64.ubuntu.22 prompt/off
2024-09-16 01:50:20,031 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['s3', 'ls', '--debug', '--endpoint=https://us-southeast-1.linodeobjects.com']
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_timestamp_parser at 0x78aa87b00b80>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function register_uri_param_handler at 0x78aa88430a40>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_binary_formatter at 0x78aa87b8c400>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function no_pager_handler at 0x78aa884cfd80>
2024-09-16 01:50:20,031 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x78aa88440360>
2024-09-16 01:50:20,033 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2024-09-16 01:50:20,034 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function attach_history_handler at 0x78aa87d6b2e0>
2024-09-16 01:50:20,034 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_json_file_cache at 0x78aa87d1c2c0>
2024-09-16 01:50:20,034 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x78aa87b02b60>
2024-09-16 01:50:20,034 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x78aa87bc5c10>>
2024-09-16 01:50:20,034 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3_ls: calling handler <function add_waiters at 0x78aa87b02b60>
2024-09-16 01:50:20,034 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3_ls: calling handler <bound method AliasSubCommandInjector.on_building_command_table of <awscli.alias.AliasSubCommandInjector object at 0x78aa87bc5c10>>
2024-09-16 01:50:20,035 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.paths: calling handler <awscli.paramfile.URIArgumentHandler object at 0x78aa87f21310>
2024-09-16 01:50:20,035 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.anonymous: calling handler <awscli.paramfile.URIArgumentHandler object at 0x78aa87f21310>
2024-09-16 01:50:20,035 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.page-size: calling handler <awscli.paramfile.URIArgumentHandler object at 0x78aa87f21310>
2024-09-16 01:50:20,035 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.human-readable: calling handler <awscli.paramfile.URIArgumentHandler object at 0x78aa87f21310>
2024-09-16 01:50:20,035 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x78aa8850c290>
2024-09-16 01:50:20,035 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.summarize: calling handler <awscli.paramfile.URIArgumentHandler object at 0x78aa87f21310>
2024-09-16 01:50:20,035 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.ls: calling handler <awscli.argprocess.ParamShorthandParser object at 0x78aa8850c290>
2024-09-16 01:50:20,035 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.ls.request-payer: calling handler <awscli.paramfile.URIArgumentHandler object at 0x78aa87f21310>
2024-09-16 01:50:20,035 - MainThread - botocore.utils - DEBUG - IMDS ENDPOINT: http://169.254.169.254/
2024-09-16 01:50:20,036 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 169.254.169.254:80
2024-09-16 01:50:21,037 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/api/token: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
Traceback (most recent call last):
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/httpsession.py", line 448, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/awsrequest.py", line 94, in _send_request
    rval = super(AWSConnection, self)._send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/awsrequest.py", line 122, in _send_output
    self.send(msg)
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/awsrequest.py", line 206, in send
    return super(AWSConnection, self).send(str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x78aa87109e10>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/utils.py", line 384, in _fetch_metadata_token
    response = self._session.send(request.prepare())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/httpsession.py", line 483, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token"
2024-09-16 01:50:21,042 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTP connection (2): 169.254.169.254:80
2024-09-16 01:50:22,044 - MainThread - botocore.utils - DEBUG - Caught retryable HTTP exception while making metadata service request to http://169.254.169.254/latest/meta-data/placement/availability-zone/: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/placement/availability-zone/"
Traceback (most recent call last):
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/httpsession.py", line 448, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/awsrequest.py", line 94, in _send_request
    rval = super(AWSConnection, self)._send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/awsrequest.py", line 122, in _send_output
    self.send(msg)
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/awsrequest.py", line 206, in send
    return super(AWSConnection, self).send(str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/qp5zys77biz7imbk6yy85q5pdv7qk84j-python3-3.11.6/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/nix/store/jax6v9hcsr1gslii6fw6cx9v06ghsrqz-python3.11-urllib3-1.26.18/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x78aa871dcc50>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/utils.py", line 432, in _get_request
    response = self._session.send(request.prepare())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/httpsession.py", line 483, in send
    raise ConnectTimeoutError(endpoint_url=request.url, error=e)
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://169.254.169.254/latest/meta-data/placement/availability-zone/"
2024-09-16 01:50:22,046 - MainThread - awscli.utils - DEBUG - Max number of attempts exceeded (1) when attempting to retrieve data from metadata service.
2024-09-16 01:50:22,047 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2024-09-16 01:50:22,047 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2024-09-16 01:50:22,047 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role-with-web-identity
2024-09-16 01:50:22,047 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: sso
2024-09-16 01:50:22,047 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2024-09-16 01:50:22,047 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2024-09-16 01:50:22,049 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/data/endpoints.json
2024-09-16 01:50:22,058 - MainThread - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x78aa891b87c0>
2024-09-16 01:50:22,065 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/data/s3/2006-03-01/service-2.json
2024-09-16 01:50:22,075 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/data/s3/2006-03-01/endpoint-rule-set-1.json
2024-09-16 01:50:22,077 - MainThread - botocore.loaders - DEBUG - Loading JSON file: /nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/data/partitions.json
2024-09-16 01:50:22,078 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x78aa898ba8e0>
2024-09-16 01:50:22,078 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x78aa898ba660>
2024-09-16 01:50:22,080 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2024-09-16 01:50:22,082 - MainThread - botocore.utils - DEBUG - Registering S3 region redirector handler
2024-09-16 01:50:22,082 - MainThread - botocore.utils - DEBUG - Registering S3Express Identity Resolver
2024-09-16 01:50:22,082 - MainThread - botocore.hooks - DEBUG - Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x78aa891e8fe0>
2024-09-16 01:50:22,082 - MainThread - botocore.hooks - DEBUG - Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x78aa86ac13d0>>
2024-09-16 01:50:22,082 - MainThread - botocore.regions - DEBUG - Calling endpoint provider with parameters: {'Region': 'aws-global', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'https://us-southeast-1.linodeobjects.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': False, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2024-09-16 01:50:22,082 - MainThread - botocore.regions - DEBUG - Endpoint provider result: https://us-southeast-1.linodeobjects.com
2024-09-16 01:50:22,082 - MainThread - botocore.regions - DEBUG - Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2024-09-16 01:50:22,082 - MainThread - botocore.regions - DEBUG - Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2024-09-16 01:50:22,082 - MainThread - botocore.hooks - DEBUG - Event provide-client-params.s3.ListBuckets: calling handler <function base64_decode_input_blobs at 0x78aa87b8c4a0>
2024-09-16 01:50:22,082 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <function validate_bucket_name at 0x78aa891bad40>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <function remove_bucket_from_url_paths_from_model at 0x78aa891e8e00>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x78aa86ac13d0>>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <bound method S3ExpressIdentityResolver.inject_signing_cache_key of <botocore.utils.S3ExpressIdentityResolver object at 0x78aa86ac1b90>>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-parameter-build.s3.ListBuckets: calling handler <function generate_idempotent_uuid at 0x78aa891bab60>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <function add_expect_header at 0x78aa891bb100>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <bound method S3ExpressIdentityResolver.apply_signing_cache_key of <botocore.utils.S3ExpressIdentityResolver object at 0x78aa86ac1b90>>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.ListBuckets: calling handler <function inject_api_version_header_if_needed at 0x78aa891e8680>
2024-09-16 01:50:22,083 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=ListBuckets) with params: {'url_path': '/', 'query_string': '', 'method': 'GET', 'headers': {'User-Agent': 'aws-cli/2.14.2 Python/3.11.6 Linux/6.8.0-101041-tuxedo source/x86_64.ubuntu.22 prompt/off command/s3.ls'}, 'body': b'', 'url': 'https://us-southeast-1.linodeobjects.com/', 'context': {'client_region': 'aws-global', 'client_config': <botocore.config.Config object at 0x78aa86a65850>, 'has_streaming_input': False, 'auth_type': 'v4', 'signing': {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}, 'endpoint_properties': {'authSchemes': [{'disableDoubleEncoding': True, 'name': 'sigv4', 'signingName': 's3', 'signingRegion': 'us-east-1'}]}, 's3_redirect': {'redirected': False, 'bucket': None, 'params': {}}}}
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.ListBuckets: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x78aa87f57c50>>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.ListBuckets: calling handler <function set_operation_specific_signer at 0x78aa891baa20>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <function remove_arn_from_signing_path at 0x78aa891e8f40>
2024-09-16 01:50:22,083 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.ListBuckets: calling handler <bound method S3ExpressIdentityResolver.resolve_s3express_identity of <botocore.utils.S3ExpressIdentityResolver object at 0x78aa86ac1b90>>
2024-09-16 01:50:22,083 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2024-09-16 01:50:22,083 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
GET
/

host:us-southeast-1.linodeobjects.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20240916T005022Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2024-09-16 01:50:22,083 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20240916T005022Z
20240916/us-east-1/s3/aws4_request
0edb3d54dc44d23013c3cf4bc0b07548ac3f5cd7a5709c3223d8e4340578cd55
2024-09-16 01:50:22,083 - MainThread - botocore.auth - DEBUG - Signature:
e25258101f42b6c73084ec0cba9b188a8dc46038cffa6321a3d40e3bf1831639
2024-09-16 01:50:22,083 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=https://us-southeast-1.linodeobjects.com/, headers={'User-Agent': b'aws-cli/2.14.2 Python/3.11.6 Linux/6.8.0-101041-tuxedo source/x86_64.ubuntu.22 prompt/off command/s3.ls', 'X-Amz-Date': b'20240916T005022Z', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=88UW1X7FZ73SDO3DUSAV/20240916/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e25258101f42b6c73084ec0cba9b188a8dc46038cffa6321a3d40e3bf1831639'}>
2024-09-16 01:50:22,083 - MainThread - botocore.httpsession - DEBUG - Certificate path: /nix/store/vv0caanhxkc54cb8a9pw5x8ing89ibz7-awscli2-2.14.2/lib/python3.11/site-packages/awscli/botocore/cacert.pem
2024-09-16 01:50:22,083 - MainThread - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): us-southeast-1.linodeobjects.com:443
2024-09-16 01:50:22,555 - MainThread - urllib3.connectionpool - DEBUG - https://us-southeast-1.linodeobjects.com:443 "GET / HTTP/1.1" 200 371
2024-09-16 01:50:22,555 - MainThread - botocore.parsers - DEBUG - Response headers: {'Date': 'Mon, 16 Sep 2024 00:50:22 GMT', 'Content-Type': 'application/xml', 'Connection': 'keep-alive', 'x-amz-request-id': 'tx000001c57c8399cd5ed7d-0066e780ce-88e45948-default', 'Content-length': '371'}
2024-09-16 01:50:22,555 - MainThread - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>f157ab5f-9497-41e8-85f1-6039f24c64d3</ID><DisplayName>f157ab5f-9497-41e8-85f1-6039f24c64d3</DisplayName></Owner><Buckets><Bucket><Name>20230229-us</Name><CreationDate>2024-02-29T15:09:29.006Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>'
2024-09-16 01:50:22,556 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <bound method RetryHandler.needs_retry of <botocore.retries.standard.RetryHandler object at 0x78aa86ac17d0>>
2024-09-16 01:50:22,557 - MainThread - botocore.retries.standard - DEBUG - Not retrying request.
2024-09-16 01:50:22,557 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x78aa86ac13d0>>
2024-09-16 01:50:22,557 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <function enhance_error_msg at 0x78aa87b007c0>
2024-09-16 01:50:22,557 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <bound method RetryQuotaChecker.release_retry_quota of <botocore.retries.standard.RetryQuotaChecker object at 0x78aa86ac0950>>
